### ISSUE TITLE
onConsentChange callbacks do not trigger beyond the first time a user sets consent

### ISSUE THREAD

**Issue by ripecosta** [guardian/consent-management-platform#412]
**Use case**: A user with a set consent state resurfaces the CMP banner and changes their consent state.

**Expected behaviour**: The `onConsentChange` triggers the callbacks with the new consent state.

**Observed behaviour**: `onConsentChange` does not trigger the callbacks.

**Impact**: New consent state only gets acted upon after the page reloads. Problematic for SPAs where navigation does not trigger a page load.

Implementation: [Here](https://github.com/guardian/manage-frontend/blob/main/app/client/components/analytics.tsx)

Note: Seeing this with the TCFv2 banner. Did not test others.

**Comment by ripecosta** [comment]
After a chat with @ioanna0 we both suspect the origin of this issue might be in the use of dynamic imports, which could be creating two instances of the CMP library, one created when it gets imported into the `analytics.tsx` file linked above and a second one created by the dynamic import in the footer to resurface the banner.

I will remove the dynamic imports (they have recently become unnecessary) and report back with the results.

**Comment by ashishpuliyel** [comment]
@ripecosta Did this have the intended effect?

**Comment by ripecosta** [comment]
@ashishpuliyel Couldn't get to this yet as the team had other more pressing matters. I'm hoping I can get to it soon though.

**Comment by mxdvl** [comment]
There’s some hope that #431 fixes it. That’s available in release `^6.11.3`

**Comment by ripecosta** [comment]
@mxdvl Looking at your change it indeed looks like it could fix the cause of this bug. I'll test it as soon as I get the opportunity. Thanks for flagging.

**Comment by ripecosta** [comment]
@mxdvl @ashishpuliyel The latest version fixed the bug with needing to remove the dynamic import. Thank you for looking into it! Closing this issue.
